image: registry.gitlab.com/kolanich-subgroups/docker-images/fixed_python:latest
#image: registry.gitlab.com/kolanich-subgroups/docker-images/python_graal:latest

stages:
  - build
  - trigger
  - test

variables:
  DOCKER_DRIVER: overlay2
  SAST_ANALYZER_IMAGE_TAG: latest
  SAST_DISABLE_DIND: "true"

include:
  - template: SAST.gitlab-ci.yml
  #- template: DAST.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml
  #- template: Container-Scanning.gitlab-ci.yml
  #- template: Dependency-Scanning.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

build:
  tags:
    - shared
    - linux
  stage: build
  variables:
    GIT_DEPTH: "1"
    PYTHONUSERBASE: ${CI_PROJECT_DIR}/python_user_packages

  before_script:
    - export PATH="$PATH:$PYTHONUSERBASE/bin" # don't move into `variables`

  script:
    - python3 setup.py bdist_wheel
    - mv ./dist/*.whl ./dist/patchSeq-0.CI-py3-none-any.whl
    - pip install --user --upgrade --pre ./dist/*.whl
    - coverage run -a --source=patchSeq -m pytest --junitxml=./rspec.xml ./tests/tests.py
    #- coverage run -a --source=patchSeq -m patchSeq
    - coverage xml

  cache:
    paths:
      - /usr/local/site-packages
      - /usr/local/lib/python*/site-packages

  artifacts:
    paths:
      - dist
    reports:
      junit: ./rspec.xml
      cobertura: ./coverage.xml

